### PR TITLE
Adding remove icon for checklist items

### PR DESCRIPTION
**Pull request by alexburner**
Finally :-D

### CODE REVIEW

**Comment by tgrosinger** [comment]
Works great! Thank you.
Is there any way we can move the delete icon up to be centered with the checkbox?

It would also be super cool if the icon was visible any time you were hovering over the list item, but not sure if that is possible.

**Comment by tgrosinger** [comment]
Oh, and bumping the version in [plugin.info](https://github.com/tgrosinger/tw5-checklist/blob/master/plugin.info).

**Comment by alexburner** [comment]
Commit amended:
1. bumped version number
2. hovering over list item brings up "X" (it was easier than I thought whoops)
3. delete icon _should_ be centered with checkbox but I'm not sure, @tgrosinger pls let me know how it looks on ubuntu/chrome

**Comment by alexburner** [comment]
Commit amended:
Always-red "X" felt too danger zone. Now it is only red on hover.

**Comment by alexburner** [comment]
Commit amended:
Removed sad attempt at aligning checkboxes, hoping for the best

**Pull request merged**
