### PR TITLE
fixed linebreak before '+' in latest tiddlywiki/browsers

### PR DESCRIPTION
**Pull request by rimi**

### CODE REVIEW

**Comment by tgrosinger** [comment]
Do you happen to have an example of this running that I can look at which demonstrates the difference?

**Comment by rimi** [comment]
i can provide screenshots - that was how it looked for me (all tested river-widths in latest FF and Chrome) beofre:

grafik

and after:

grafik

Mirko

**Comment by tgrosinger** [comment]
Sorry for the delay. I just got around to testing this. What causes the break that you are fixing? When I am building it, this change makes the plus very far unaligned to the left.

**Comment by tgrosinger** [comment]
Closing from inactivity.

**Pull request closed without merging**
